# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

---

name: Continuous Integration and Deployment

on: push

jobs:
  get_versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"pds4_version\":[ \"1.14.0.0\", \"1.15.0.0\" ]}"

  build: # job 1
    name: 'LDD Build'
    runs-on: ubuntu-latest
    if: github.actor != 'pdsen-ci'

    strategy:
      matrix:
        pds4_version: ${{fromJson(needs.get_versions.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Check
        run: |
          echo "FOOO: " ${{ matrix.pds4_version }}
