# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

---

name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        run: |
          while read -r line; do
              if [[ ! -z "$line" ]]; then
                  versions=$versions'"'$line'"',
              fi
          done < $GITHUB_WORKSPACE/pds4_versions.txt
          foo=[${versions::-1}]
          echo "{\"pds4_version\":${foo}}"
          echo "::set-output name=versions::$foo"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #       pds4_version: ${{needs.job1.outputs.versions}}
    steps:
    - run:
        echo ${{needs.job1.outputs.versions}}
        echo ${{matrix.pds4_version}}
