# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

---

name: Continuous Integration and Deployment

on:
  push:
    branches:
      - master
      # - pulls/()
  pull_request:
    types: [opened, edited, reopened]

jobs:
  build:
    name: "Generate and Test Dictionaries (development build)"
    runs-on: ubuntu-latest

    env:
      REG_TEST_DIR: ${{ format('{0}/{1}/', github.workspace, 'test') }}
      DEPLOY_DIR: ${{ format('{0}/{1}/', github.workspace, 'build/development') }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Get Latest LDDTool and Validate Versions
        run: |
          echo ::set-env name=LDDTOOL_VERSION::$(curl --silent "https://api.github.com/repos/NASA-PDS/pds4-information-model/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')
          echo ::set-env name=VALIDATE_VERSION::$(curl --silent "https://api.github.com/repos/NASA-PDS/validate/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')

      - name: Get Latest IM Version
        run: |
          echo ::set-env name=IM_VERSION::$(curl --silent "https://raw.githubusercontent.com/NASA-PDS/pds4-information-model/v${{ env.LDDTOOL_VERSION }}/model-ontology/src/ontology/Data/config.properties" | grep 'infoModelVersionId' | awk -F= '{print $NF}')

      - name: Download and Unpack LDDTool
        run: |
          wget --directory-prefix=/tmp https://github.com/NASA-PDS/pds4-information-model/releases/download/v$LDDTOOL_VERSION/lddtool-$LDDTOOL_VERSION-bin.tar.gz
          tar -xf /tmp/lddtool-$LDDTOOL_VERSION-bin.tar.gz -C /tmp/

      - name: Generate Dictionaries
        run: |
          echo "+++ Cleanup development versions if they exist"
          mkdir -p $DEPLOY_DIR; cd $DEPLOY_DIR; rm -fr ./*

          echo "+++ Generate dictionaries"
          dependencies_dir=$GITHUB_WORKSPACE/src/dependencies
          if [ -d "$dependencies_dir" ]; then
            files="$dependencies_dir/*/src/*IngestLDD*.xml $GITHUB_WORKSPACE/src/*IngestLDD*.xml"
          else
            files="$GITHUB_WORKSPACE/src/*IngestLDD*.xml"
          fi

          echo "+++ Generating dictionaries for $files"
          /tmp/lddtool-$LDDTOOL_VERSION/bin/lddtool -plJn $files

      - name: Validate Schemas and Schematrons
        run: |
          wget --directory-prefix=/tmp https://github.com/NASA-PDS/validate/releases/download/v$VALIDATE_VERSION/validate-${VALIDATE_VERSION}-bin.tar.gz
          tar -xf /tmp/validate-${VALIDATE_VERSION}-bin.tar.gz -C /tmp/

          /tmp/validate-$VALIDATE_VERSION/bin/validate --skip-content-validation -R pds4.label -x $DEPLOY_DIR/*.xsd -S *.sch -t $DEPLOY_DIR/*.xml
        id: validate_schemas
        continue-on-error: True

      # - name: Complete Regression Tests (if applicable)
      #   run: |
      #     wget --directory-prefix=/tmp https://github.com/NASA-PDS/validate/releases/download/v$VALIDATE_VERSION/validate-${VALIDATE_VERSION}-bin.tar.gz
      #     tar -xf /tmp/validate-${VALIDATE_VERSION}-bin.tar.gz

      #     if [ -d "$TEST_DIR" ]; then
      #       # Run test expected valid
      #       /tmp/validate-$VALIDATE_VERSION/bin/validate --skip-content-validation -R pds4.label -x $DEPLOY_DIR/*.xsd -S $DEPLOY_DIR/*.sch -t $REG_TEST_DIR/*VALID.xml

      #       # Run tests expected invalid
      #       # TBD some regression test FAIL
      #     fi
      #   id: regression_tests
      #   continue-on-error: True

      - name: Add Dictionaries to Pull Request
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git config --local github.token ${{ secrets.GITHUB_TOKEN }}
            git add $DEPLOY_DIR
            git commit -m "Auto-generated dictionaries from Github Actions"
            git push
        if: ${{ success() }}
