# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

---

name: Generate Dictionaries with LDDTool

on: [push, pull_request]
  #pull_request:
  #  types: opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download and Unpack LDDTool
      run: |
         wget --directory-prefix=/tmp https://github.com/NASA-PDS-Incubator/pds4-information-model/releases/download/v10.1.2/lddtool-10.1.2-bin.tar.gz
         tar -xf /tmp/lddtool-10.1.2-bin.tar.gz -C /tmp/

    - name: Generate Dictionaries
      run: |
        mkdir -p build; cd build
        /tmp/lddtool-10.1.2/bin/lddtool -plJnl $(pwd)/../src/dependencies/*/src/*IngestLDD*.xml $(pwd)/../src/*IngestLDD*.xml

    - name: Add Dictionaries to Pull Request
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local github.token ${{ secrets.GITHUB_TOKEN }}
          git add .
          git commit -m "Add changes"
          git push