# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

---

name: Generate Dictionaries with LDDTool

on: [push, pull_request]
#  pull_request:
#    types: opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Download and Unpack LDDTool
      run: |
         wget https://github.com/NASA-PDS-Incubator/pds4-information-model/releases/download/v10.1.2/lddtool-10.1.2-bin.tar.gz
         tar -xf lddtool-10.1.2-bin.tar.gz

    - name: Generate Dictionaries
      run: |
         lddtool-10.1.2/bin/lddtool --help
         lddtool-10.1.2/bin/lddtool -plJnl PDS4_IMG_IngestLDD_1A10.xml


    - name: Add Dictionaries to Pull Request
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local github.token ${{ secrets.GITHUB_TOKEN }}
          git commit -m "Add changes" -a
