# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

---

name: Continuous Integration and Deployment

on:
  pull_request:
    types: opened

jobs:
  build:
    name: "Build Dictionaries"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Download and Unpack LDDTool
        run: |
          export lddtool_version=$(curl --silent "https://api.github.com/repos/NASA-PDS-Incubator/pds4-information-model/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')
          wget --directory-prefix=/tmp https://github.com/NASA-PDS-Incubator/pds4-information-model/releases/download/v${lddtool_version}/lddtool-${lddtool_version}-bin.tar.gz
          tar -xf /tmp/lddtool-${lddtool_version}-bin.tar.gz -C /tmp/

      - name: Generate Dictionaries
        run: |
          mkdir -p build; cd build
          /tmp/lddtool-${lddtool_version}/bin/lddtool -plJnl $(pwd)/../src/dependencies/*/src/*IngestLDD*.xml $(pwd)/../src/*IngestLDD*.xml

      # - name: Complete Regression Tests
      #   run: |
      #     export validate_version=$(curl --silent "https://api.github.com/repos/NASA-PDS-Incubator/validate/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')
      #     wget --directory-prefix=/tmp https://github.com/NASA-PDS-Incubator/validate/releases/download/v${validate_version}/validate-${validate_version}-bin.tar.gz
      #     tar -xf /tmp/validate-${validate_version}-bin.tar.gz

      #     /tmp/validate-${validate_version}/bin/validate --skip-content-validation *.xml  # TODO - do not want to validate all XML

      #     if [ -d "$(pwd)/../test" ]; then
      #       export validate_version=$(curl --silent "https://api.github.com/repos/NASA-PDS-Incubator/validate/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')
      #       wget --directory-prefix=/tmp https://github.com/NASA-PDS-Incubator/validate/releases/download/v${validate_version}/validate-${validate_version}-bin.tar.gz
      #       tar -xf /tmp/validate-${validate_version}-bin.tar.gz
      #     fi

      - name: Add Dictionaries to Pull Request
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git config --local github.token ${{ secrets.GITHUB_TOKEN }}
            git add .
            git commit -m "Auto-generated dictionaries from Github Actions"
            git push
